language: node_js
node_js:
- '5'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- ./node_modules/.bin/bower install --allow-root
# - ./node_modules/protractor/bin/webdriver-manager update --standalone --firefox
# - ./node_modules/protractor/bin/webdriver-manager start 2>&1 &
# - sleep 3
script:
# - ./node_modules/bithound/bin/bithound check git@github.com:mrnz/vin-ver2.git
# - grunt templates
- gulp unit-travis
# - grunt build
# - grunt e2e-travis
# - if [ "$TRAVIS_BRANCH" == "master" ]; then grunt ftp_push --ftpUser=$USERNAME --ftpPass=$PASSWORD; fi
after_success:
  - cat coverage/*/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js