sudo: false
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin
notifications:
  email: false
language: android
android:
  components:
    - build-tools-19.1.0
    # The SDK version used to compile your project
    - android-19
    - android-23
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
before_script:
- nvm install 5
- npm install -g cordova
- npm install -g ionic
- npm install -g appium
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- ./node_modules/.bin/bower install --allow-root
- appium &
- sleep 5
- echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
- sleep 3
script:
- gulp unit-travis
- ionic platform add android
- ls /home/travis/build/mrnz/gjv/
- ls /home/travis/build/mrnz/gjv/platforms
- ls /home/travis/build/mrnz/gjv/platforms/android
- ls /home/travis/build/mrnz/gjv/platforms/android/build
- ls /home/travis/build/mrnz/gjv/platforms/android/build/outputs
- gulp build-android-travis
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb devices
- adb shell input keyevent 82 &
- ./node_modules/protractor/bin/protractor protractor.conf.js
after_success:
  - cat coverage/*/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js